In [6]:
import numpy as np

In [52]:
# seq = input()

In [8]:
# seq1 = seq.split()[0]
# seq2= seq.split()[1]

In [44]:
seq1 = 'ACTTCGACT'
seq2 = 'GATCGAAT'

In [53]:
match_score = np.zeros((4, 4))
match_score[0][0] = 3
match_score[0][1] = match_score[1][0] = -3
match_score[0][2] = match_score[2][0] = -2
match_score[0][3] = match_score[3][0] = -1
match_score[1][1] = 4
match_score[1][2] = match_score[2][1] = -1
match_score[1][3] = match_score[3][1] = 2
match_score[2][2] = 5
match_score[2][3] = match_score[3][2] = 0
match_score[3][3] = 6
print(match_score)

[[ 3. -3. -2. -1.]
 [-3.  4. -1.  2.]
 [-2. -1.  5.  0.]
 [-1.  2.  0.  6.]]


In [54]:
letters = {"A" : 0, "T" : 1, "C" : 2, "G" : 3}

In [55]:
# def match_score(seq1, seq2):
#     if seq1 == seq2:
#         return 1
#     elif seq1 == '_' or seq2 == '_':
#         return -1
#     else:
#         return -1

In [56]:
def global_alignment(seq1, seq2):
    n = len(seq1)  
    m = len(seq2)
    mismatch_penalty = -1
    gap_penalty = -1
    score = np.zeros((m+1, n+1))
    
    for i in range(m + 1):
        score[i][0] = gap_penalty * i

    for j in range(n + 1):
        score[0][j] = gap_penalty * j
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = score[i - 1][j - 1] + match_score[letters[seq1[j-1]]][letters[seq2[i-1]]]
            delete = score[i - 1][j] + gap_penalty
            insert = score[i][j - 1] + gap_penalty
            score[i][j] = max(match, delete, insert)
            
    align1 = ""
    align2 = ""
    i = m
    j = n

    while i > 0 and j > 0:
        score_current = score[i][j]
        score_diagonal = score[i-1][j-1]
        score_up = score[i][j-1]
        score_left = score[i-1][j]
        
        if score_current == score_diagonal + match_score[letters[seq1[j-1]]][letters[seq2[i-1]]]:
            align1 += seq1[j-1]
            align2 += seq2[i-1]
            i -= 1
            j -= 1
        elif score_current == score_up + gap_penalty:
            align1 += seq1[j-1]
            align2 += '_'
            j -= 1
        elif score_current == score_left + gap_penalty:
            align1 += '_'
            align2 += seq2[i-1]
            i -= 1

    while j > 0:
        align1 += seq1[j-1]
        align2 += '_'
        j -= 1
    while i > 0:
        align1 += '_'
        align2 += seq2[i-1]
        i -= 1
    
    return (align1[::-1], align2[::-1])

In [57]:
align1, align2 = global_alignment(seq1, seq2)
print(align1 + " " + align2)

_ACTTCGACT GA__TCGAAT


Поменяем одно число в матрице

In [58]:
match_score[3][0] = 10

In [59]:
align1, align2 = global_alignment(seq1, seq2)
print(align1 + " " + align2)

_ACTTC_GACT GA__TCGAA_T


Выравнивание поменялось